sudo: required
language: bash

before_install:

 - sudo apt-get -y update
 - sudo apt-get install -y perl-*
 - sudo apt-get install -y libcam-pdf-perl
 - sudo apt-get install -y build-essential
 - sudo apt-get install -y sendmail
 - CPAN MIME::Lite
 - CPAN MIME::Lite::TT::HTML

script:
 - ./emailscript.pl

notifications:
  slack:
    rooms:
      - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
